name: py38
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.6.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.16.0
  - click=8.1.7
  - cryptography=41.0.5
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - debugpy=1.8.0
  - decorator=5.1.1
  - executing=2.0.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - google-pasta=0.2.0
  - grpc-cpp=1.48.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - keras-preprocessing=1.1.2
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.44.1
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - markdown=3.4.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - oauthlib=3.2.2
  - openssl=3.1.4
  - opt_einsum=3.3.0
  - packaging=23.2
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.0.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pyzmq=25.1.1
  - re2=2022.06.01
  - readline=8.2
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-gpu=2.4.1
  - termcolor=2.1.0
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - urllib3=1.26.18
  - wcwidth=0.2.12
  - werkzeug=2.2.3
  - wheel=0.41.3
  - wrapt=1.14.1
  - xz=5.4.2
  - yarl=1.8.1
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - alembic==1.12.1
      - altair==5.1.2
      - anyio==4.1.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - babel==2.13.1
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - boto==2.49.0
      - boto3==1.29.6
      - botocore==1.32.6
      - bs4==0.0.1
      - cachetools==5.3.2
      - chardet==5.2.0
      - charset-normalizer==2.1.1
      - cmake==3.27.7
      - coccoctokenizer==1.4
      - colorama==0.4.6
      - colorlog==6.7.0
      - comm==0.2.0
      - contourpy==1.1.1
      - courlan==0.9.5
      - cycler==0.12.1
      - cython==3.0.6
      - dateparser==1.2.0
      - datetime==5.3
      - defusedxml==0.7.1
      - exceptiongroup==1.2.0
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - findspark==2.0.1
      - fonttools==4.45.0
      - fqdn==1.5.1
      - future==0.18.3
      - gdown==4.7.1
      - gensim==3.8.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - greenlet==3.0.1
      - grpcio==1.59.3
      - htmldate==1.6.0
      - idna==3.6
      - importlib-resources==6.1.1
      - ipython==8.12.3
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.10.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - justext==3.0.0
      - keras==2.15.0
      - keras-tuner==1.4.6
      - kiwisolver==1.4.5
      - kt-legacy==1.0.5
      - langcodes==3.3.0
      - lxml==4.9.3
      - mako==1.3.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.6.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nltk==3.8.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - optuna==3.4.0
      - optuna-integration==3.5.0
      - overrides==7.4.0
      - pandocfilters==1.5.0
      - pexpect==4.9.0
      - pickle-mixin==1.0.2
      - pickle5==0.0.11
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.18.0
      - prometheus-client==0.19.0
      - protobuf==3.20.3
      - psutil==5.9.6
      - py-vncorenlp==0.1.4
      - py4j==0.10.9.7
      - pyarrow==14.0.1
      - pyasn1==0.5.1
      - pydeck==0.8.1b0
      - pyjnius==1.6.1
      - pympler==1.0.1
      - pyparsing==3.1.1
      - pyspark==3.5.0
      - python-crfsuite==0.9.9
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.31.0
      - regex==2023.10.3
      - requests==2.28.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.13.1
      - s3transfer==0.7.0
      - scikit-learn==1.3.2
      - scipy==1.9.3
      - seaborn==0.13.0
      - send2trash==1.8.2
      - smart-open==1.9.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.23
      - stack-data==0.6.3
      - streamlit==1.24.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.3.0
      - terminado==0.18.0
      - terminaltables==3.1.10
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tld==0.13
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - tqdm==4.64.1
      - trafilatura==1.6.3
      - types-python-dateutil==2.8.19.14
      - tzdata==2023.3
      - tzlocal==4.3.1
      - underthesea==6.8.0
      - underthesea-core==1.0.4
      - unicode==2.9
      - unidecode==1.3.7
      - ur-gadget==0.0.4
      - uri-template==1.3.0
      - validators==0.22.0
      - vncorenlp==1.0.3
      - vnnews==0.0.1
      - vws==0.0.1
      - watchdog==3.0.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - widgetsnbextension==4.0.9
      - zope-interface==6.1
      - numpy==1.19.2
      - pandas==1.3.3

